### ISSUE TITLE
Notifications support

### ISSUE THREAD

**Issue by ekzobrain** [millerf/django-channels-jsonrpc#10]
It would be great to implement inbound (and outbound) notifications.
I could make a pull-request. I think inbound notifications may be processed by the same __process method (but not return any value, so nothing will be sent back) and handlers may be defined with the same JsonRpcWebsocketConsumer.rpc_method() decorator... what do you think?

By outbound notifications i mean possibility to send JsonRpc notifications to "reply_channel" or to Groups (make implementation bi-directional in some way). I think a good starting point would be to create some helper method like "create_notification(method, params)" that just takes method name and params and returnes a correct JSON structure defined in JsonRpc protocol, so that it may be used like this:
```python
original_message.reply_channel.send({"text": create_notification(method, params)})
Group("xxx").send({"text": create_notification(method, params)})
```

**Comment by millerf** [comment]
I was thinking using another decorator, such as JsonRpcWebsocketConsumer.rpc_notification(), that would basically use the same logic as you described. Maybe wrapping JsonRpcWebsocketConsumer.rpc_method() to make sure it doesn't return anything, and throw an Exception if it ever does.

Outbound notification what I would personnaly need. So yes, it will need to be implemented at some point. I am bound to look into that later on, as I don't know Channels enough. I think we will need to find a nice way to add 'clients' to groups in order to be able to send the notification to only specific clients. But I agree  something like:
`Group("xxx").send_notification(method, params)`
would be needed.

Thanks for the awesome feedback. Feel free to create a Pull-request.

**Comment by ekzobrain** [comment]
Add client to groups (and broadcast to them) is a basic Channels feature: https://channels.readthedocs.io/en/stable/getting-started.html#groups
The only think that should be implemented is possibility to transparently broadcast messages in notification format. Currently you have an "group_send" class method, which is not documented and used anywhere. But group notifications may be implemented the same way, for example:
```python
@classmethod
def group_notify(cls, name, method, params=None):
    content = {
        'jsonrpc': '2.0',
        'method': method
    }
    if params:
        content['params'] = params
    super().group_send(name, json.dumps(content, cls=cls.json_encoder_class))
```

**Comment by millerf** [comment]
Feel free to remove the group_send. And replace it with group_notify.

group_send() doesn't have any business being here, except for notifications. It must have been copied from the class I based JsonRpcWebsocketConsumer upon.

We should also create a "private" method to build a response object, just not to have 
```
content = {
        'jsonrpc': '2.0',
        'method': method
    }
```
everywhere.

**Comment by ekzobrain** [comment]
Of course encoding/decoding should be separated from processing and deduplicated, it was just an example that shows complete logic.

**Comment by millerf** [comment]
I was just pointing it out to have a trace of it :)

**Comment by ekzobrain** [comment]
I thought about outbound notifications and came up with this solution:
Two new static methods
JsonRpcConsumer.notify_channel(message.reply_channel, method, params)
JsonRpcConsumer.notify_group(group_name, method, params)

This will be very easy and straightforward to implement and will not require extending any Channels built-in objects.

**Comment by ekzobrain** [comment]
What do you think?

**Comment by millerf** [comment]
Notify channel would notify the "current" client? Is that it?

**Comment by ekzobrain** [comment]
Yes, that's it. Use cases are:
Send notification directry from "connect" callback.
Send outbound notification from inbound notification handler.

**Comment by millerf** [comment]
I finished implementation of notifications (in and out). I will work on the documentation tomorrow.
Let me know what you think:
https://github.com/millerf/django-channels-jsonrpc/commits/notifications

I made a copy/paste of the __process() function. I will clean that up when I will have merged your modifications. 

While testing, I also couldn't find how to make sure I was passing in[ those functions](https://github.com/millerf/django-channels-jsonrpc/blob/notifications/example/django_example/tests.py#L511): Mock wouldn't let me patch them. If you have any ideas...

**Comment by ekzobrain** [comment]
I think it's time to merge all together (with http support) and try it :)
Then we could think on optimizations and may be moving to json-rpc dependency.

**Comment by millerf** [comment]
Yes.
I won't have time to move to json-rpc dependency unfortunately. I need to start hammering my own project quite hard.
Merging all together will make a nice 1.2 version (minimum). We can wait for 1.2.1 to add the json-rpc module. What do you think?

**Comment by ekzobrain** [comment]
I agree. First of all we need to finalize public API. Then moving to a dependency would be quite easy without breaking compatibility.
