### ISSUE TITLE
Move all encoding/decoding/validating logic to a dependency package

### ISSUE THREAD

**Issue by ekzobrain** [millerf/django-channels-jsonrpc#11]
We could use this package http://json-rpc.readthedocs.io/en/latest/index.html (for example) as a dependency and get rid of all protocol-agnostic questions (encoding/decoding/validation). We will not have to think wheater our JSON-RPC is correct (according to the Spec) or not.

**Comment by millerf** [comment]
The drawback of this package is that it seems to bring along a lot more than simple JSON-RPC (encoder/ decoder/ validator). Let's look around if there is something more simple and maybe more flexible as well?
But we can still test...

**Comment by millerf** [comment]
Actually it looks simple than expected, let see if we can plug it nicely in the project.

**Comment by ekzobrain** [comment]
That will provide code cleanless and better JSON-RPC spec support, but it's somewhat a secondary task, first of all we need to complete HTTP calls and inbound/outbound Notifications.

**Comment by millerf** [comment]
inbound/outbound should be a breeze..
Would you be fine working on HTTP, while I do the Notifications?

**Comment by ekzobrain** [comment]
Yes, see my answer here: #8
