### ISSUE TITLE
Improve outbound notifications

### ISSUE THREAD

**Issue by ekzobrain** [millerf/django-channels-jsonrpc#15]
While using new outbound notifications in my project, I realized that our current implementation is not a completed solution:
JsonRpcConsumer.notify_group()'s "params" parameter is directly assigned to JSON-RPC "params" without any checks, that may lead to incorrect JSON output. "params" must be forced to list or dict types, at least. But using python's argument unpacking and named parameters we could make it in a better way.
In fact, we a making a JsonRpc client (asuming outbound calls), which is aimed to work ot top of Django Channels. So I think we shoud go the same way as most clients do, using Channels as an endpoint. A standart approach of all clients looks like this:

```python
client = JsonRpcClient(endpoint) #  endpoint = some http url or websocket url
client.call(method_name, param1, param2)
client.notification(method_name, param1, param2)
```
In our case it might look the same way, for example:
```python
JsonRpcClient(Group('name')).notify(method, param1, param2) # notification with positional arguments as per JSON-RPC spec
JsonRpcClient(message.reply_channel).notify(method, param1=value1, param2=value2) # notification with named arguments
```
So the solution is:

1. We introduce a new class JsonRpcClient along with our main JsonRpcConsumer.
2. We use Channels "Group" and "reply_channel" objects as possible endpoints.
3. JsonRpcClient has one method - "notify", which sends outbound notifications. We can not impelment "call" method we will not be able to retrieve response anyway.
4. When notify is called with positional arguments - we encode them as a list, and when with named - as a dict. This way we ensure that arguments are passed correctly without any type-forcing. We just need to check that user did not pass both positional and named parameters together.

I may implement it tomorrow and make a pull request, it you like this approach.

**Comment by millerf** [comment]
It does make sense...

I might freeze my version fro now as I need to move forward on my project, feel free to make a PR,a and I'll keep merging.
I think moving to version 2.0 with that modification and also the json-rpc module added. And some doc, obviously :)

**Comment by millerf** [comment]
Did you end up working on that?

**Comment by ekzobrain** [comment]
No, I did not start it yet. I just pushed a fix for current implementation bugs: #16
I'll try to do it within next few weeks.

**Comment by millerf** [comment]
Yes, I saw that. I added some comments on it as they introduced a regression in tests

**Comment by ekzobrain** [comment]
Hm, I do not see any comments in that pull request...
And generally those fixes should be fully backward-compatible, the only thing that changed really is error handling in notifications. When dealing with HTTP requests - returned status code should contain execution status, otherwise many client libraries would fail

**Comment by millerf** [comment]
I tagged you in the comments, let me know if you see them...

**Comment by ekzobrain** [comment]
No, I still do not see comments...

**Comment by millerf** [comment]
You don't see any comments in #16 ?

**Comment by ekzobrain** [comment]
Yes, I don't.

**Comment by millerf** [comment]
forgot to submit the review...
