### ISSUE TITLE
Dead Link http://channels.readthedocs.io/en/stable/generics.html#websockets

### ISSUE THREAD

**Issue by jiargei** [millerf/django-channels-jsonrpc#20]
Hej Guys!
You did a nice work with that jsonrpcconsumer... Just one question. I tried to integrate your package into my already build up project and following your documentation i realized that the link to channels is dead.
Further i realized that your requirements need channels==1.1.6 whilst the latest stable version is around 2.1.1.
So my question, did you already tested agains channels>=2.1.0

kine regards, Mr. J

**Comment by millerf** [comment]
Hi @jiargei 

I somehow missed this thread....
I will be starting again on this package very soon, and wondering if you ended up test/make it work for channels2?

**Comment by millerf** [comment]
Here it is: 
`https://github.com/millerf/django-channels2-jsonrpc`
