### ISSUE TITLE
Why threaded processing?

### ISSUE THREAD

**Issue by ekzobrain** [millerf/django-channels-jsonrpc#9]
What is the reason for executing JsonRpc in separate threads?

**Comment by millerf** [comment]
Because you don't want a request to block another one.
Json-RPC doesn't specify any sequentiality in the answers. Meaning:
-> REQUEST 1
-> REQUEST 2
can be answered:
-> RESPONSE REQUEST 2
-> RESPONSE REQUEST 1

It makes it a lot more flexible as well.

**Comment by ekzobrain** [comment]
It won't block processing next messages anyway, because they will be processed by other Channels workers. In asynchronous processing model (e.g. Tornado) it would make sense, but Channels asume synchronous processing in parallel by several workers, so i think it is unnesessary and breaks overall request processing design. Also such approach may break Channels "strict_ordering" feature, because main execution thread returns and message is then marked as processed by Channels (so it starts processing next message in the queue), whereas real method body may still be executing and that may lead to unexpected results. You have a "TEST_MODE" flag, I think it would be right to rename it to something like "USE_THREADS" and describe it in docs, but it should be force-disabled when "strict_ordering" is ON.

**Comment by millerf** [comment]
Great point. I actually didn't think about the internal threading used by Channels.
Although I think that we should disable the strict ordering by default, in order to get closer to JSON-RPC specification. I do think ordering request wouldn't make sense.
TEST_MODE needs to stay as it is. It is only used for tests, as threads make testing impossible.
But so far I agree on dropping the threading.
Thanks for you feedback. Very appreciated.

**Comment by ekzobrain** [comment]
By default strict ordering is OFF, users may want to enable it to conform some application-level sequence logic. So it is not intended to provide request/response order, but to be sure, that messages will be processed in the same order they were recieved from socket. You may look at example here: https://channels.readthedocs.io/en/stable/getting-started.html#enforcing-ordering

**Comment by millerf** [comment]
Yes, but again ordering for JSON-RPC should be implemented on the client side, meaning if you have to send a sequence of requests, you should wait to get the answer from the previous one and so on... That is the whole point of JSON-RPC, to be able to know what request was just answered.
Relying on order on the server really be bad in term of application design (on the client side) as well as performance on the server side...
I am not sure I am making my point here, but I would really disapprove having strict-ordering ON on a JsonRpcConsumer.

**Comment by ekzobrain** [comment]
I agree, and i personally do not use it :) But it should be left to user's choice as Channels feature. Unguaranteed request/response order is related not only to JSON-RPC over websocket, but to any websocket-based communication protocol.
Also, please reopen this issue so threading may be removed according to it.
